# Mittel- und Streuungswerte


```{r data, echo = FALSE, cache = TRUE}
setwd("C:/LearningR/R-Course-2015/Session_06/")
planungspausen <- read.table('../data/03-1_aeh(m).txt', header = T)
```

## Ordinale Daten

```{r median}
pause.length <- planungspausen$LAENGE

#quantile
#median -->2 F채lle f체r gerade und ungerade Anzahl der Beobachtungen
#ToDo: Warum +1??? -->Probieren an Beispielen
q1 <- sort(pause.length)[floor(0.25 * (length(pause.length) + 1))]
q2 <- sort(pause.length)[floor(0.50 * (length(pause.length) + 1))]
q3 <- sort(pause.length)[floor(0.75 * (length(pause.length) + 1))]
q1; q2; q3
```

```{r quantile}
quantile(pause.length, c(0.25, 0.50, 0.75))
quantile(pause.length, c(0.1, 0.40, 0.8))
```

```{r iqr}
IQR(pause.length) #Interquartilabstand (3.Quartil-1.Quartil=mittlere 50% der Daten, kann aber auch angepasst werden)
```


```{r mad}

mean(abs(pause.length - median(pause.length)))

mad(pause.length, const = 1)
```

```{r minmax}
max(pause.length) - min(pause.length)
mean(pause.length)
```

```{r range}
max(pause.length) - min(pause.length)
```

## Metrische Daten

```{r variance}
var(pause.length) #Varianz

sqrt(var(pause.length))
```

```{r sd}
sd(pause.length)
```

```{r var_self_implemented}
sum((pause.length - mean(pause.length))^2) / length(pause.length)
```


### Graphische Darstellung

```{r summary}
str(pause.length)
summary(pause.length)
```

```{r boxplot}
boxplot(planungspausen$LAENGE)
abline(h=mean(planungspausen$LAENGE),col="red")
```

## Aufgaben
* eigene Formel f체r die Berechnung der Standardabweichung implementieren -->separate Datei: aus Datei laden (source);
* als Boxplots die L채ngen der Lemmata und der Wortformen (in Buchstabe) in einer Graphik anzeigen lassen (2 Boxplots in einem Plot -->links/rechts).